services:
  - type: web
    name: ai-comment-generator-api
    runtime: python
    plan: free

    buildCommand: |
      pip install uv
      uv sync --frozen

    startCommand: |
      uv run uvicorn main:app --host 0.0.0.0 --port $PORT

    autoDeploy: true